### ISSUE TITLE
Dropdown, ListBox, MultiSelect: support custom filter function

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1448]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**

**Expected behavior**
Dropdown, ListBox and MultiSelect should support `filterMatchMode="custom"` with a custom `filterFunction`. Like DataTable and TreeTable do.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Fixed with: https://github.com/primefaces/primereact/issues/3039

**Comment by Qcyk** [comment]
Hi, I need add custom filter function in MultiSelect control. I need to use Regex to filter the data. I tried do this on two ways. 
1. I use filterTemplate as it is shown in documentation, but it is not possible to put regex value to option.filter(). 
`const myFilterFunction = (event, options) => {
    let _filterValue = event.target.value;
    setFilterValue(_filterValue);
    options.filter(event);
}`

2. In the filterTemplate  I call my custom method (myFilterFunction) which change the options array in MultiSelect, but in this example I have a problem with filterring. 
`<InputText value={filterValue} ref={filterInputRef} onChange={(e) => myFilterFunction(e)} />`

Is there any different way to use a custom filter method to filter data in MultiSelect control? 
I am grateful for the help. 
Regards,

**Comment by francislavoie** [comment]
@melloware I realize this is a long-closed issue, but this issue was most definitely _not_ fixed with that change. The request here is to have a custom filter function which allows the user to do arbitrary filtering of their own. The linked PR only changed the way the filterable string is composed. That's not the same thing. I want to be able to do a multi-pass filter for example, like "split the filter string by words (spaces) then check that every word appears in one of the results". That would be useful because we have tagging on our entries with text like `Blah blah [Foo]` so I want to be able to search "foo blah" and find that entry.

**Comment by melloware** [comment]
@francislavoie this was fixed by PrimeTek and not me. They considered it closed.  It sounds like your use case is different I suggest opening a new ticket as this was closed 3 years ago. 

Don't forget to include a stackblitz showing what you are trying to do.

**Comment by francislavoie** [comment]
It was definitely closed by you:

![Image](https://github.com/user-attachments/assets/dd92d57f-13ef-4706-89d7-6e5502e57574)

But anyway, reading both the OP and the comment just above mine, plus the fact that OP just 👍 my comment, I think this issue could easily just be reopened, because it was not actually solved as requested.

**Comment by VsevolodGolovanov** [comment]
Yes, this was about a custom filter function as in the ability to provide your own filtering predicate. Not about filter templates.

This is what I originally referenced about the DataTable:
```
return <Column filterField={filterField} filterMatchMode="custom" filterFunction={customFilterFunction} />;

function customFilterFunction(fieldValue: any, filterValue: string): boolean {
    ...
}
```

**Comment by melloware** [comment]
I closed the ticket but the PR was by PrimeTek. I only closed it because they forgot 😀

So I had nothing to do with this feature.

**Comment by francislavoie** [comment]
I don't see any link from this ticket to that PR other than your comment.

Can we please reopen this then?

**Comment by melloware** [comment]
@francislavoie see: https://github.com/primefaces/primereact/issues/3039 by @cetincakiroglu of primetek.

**Comment by melloware** [comment]
@francislavoie i re-opened but as you can see PrimeVue also does not support the feature you want: https://primevue.org/select/#filter

so you will most likely have to financially sponsor this via PrimeReact PRO: https://primereact.org/support/

OR provide a PR adding this capability.

Either way I look forward to it!

**Comment by melloware** [comment]
@francislavoie @VsevolodGolovanov isn't that way `onFilter` event is for: https://primereact.org/dropdown/#api.Dropdown.DropdownFilterEvent

It says its for custom filtering basically letting you take control of the filter?

**Comment by VsevolodGolovanov** [comment]
I don't think `onFilter` allows you to affect filtering. It says "Custom filter event" meaning that the `DropdownFilterEvent` is a custom `Dropdown`-specific event type.

**Comment by francislavoie** [comment]
That's not a custom filter function, it's just a filter input updating function. It does not perform filtering and just delegates it to the library. That's why filterTemplate was never a solution for this.

**Comment by melloware** [comment]
Yep PR or financial sponsoring welcome!
