### ISSUE TITLE
Button: Custom icon position & spacing

### ISSUE THREAD

**Issue by tomhendra** [primefaces/primereact#3956]
### Describe the bug

When using the `icon` prop to pass a custom SVG React component, the margin for spacing is lost and the `iconPos` prop does not function.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-wf8e7r

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 109.0.5414.87

### Steps to reproduce the behavior

1) Assign a React component that returns SVG code to a variable.
2) Pass the variable to the Button icon prop.

### Expected behavior

Spacing should be applied to the custom icon in the same way as when using Prime Icons. 
The `iconPos` prop should change the position of the custom icon.

**Comment by melloware** [comment]
Thanks for the reproducer I will fix this.

**Comment by tomhendra** [comment]
Thanks to you for responding so quickly to the issue.

**Comment by melloware** [comment]
![image](https://user-images.githubusercontent.com/4399574/212478150-6a28a89c-3310-428b-8950-d24a2de3b464.png)

**Comment by tomhendra** [comment]
Think it could use a center align but apart from that it looks great!

**Comment by melloware** [comment]
It's using the same css now so I am wondering if the issue is with the SVG itself?   Does it have spacing in the SVG?

**Comment by tomhendra** [comment]
It doesn't have any spacing.

 
<img width="238" alt="Screenshot 2023-01-14 at 23 18 49" src="https://user-images.githubusercontent.com/32566274/212499926-50d35a5d-a7ee-4a75-92f9-05590e077fc0.png">

Do you have a reproducer of where you grabbed the screenshot? — I'd be happy to have a poke around.

**Comment by tomhendra** [comment]
"Sausage fingers" as we say in the UK — didn't mean to close & reopen, ha!

**Comment by melloware** [comment]
No worries!

**Comment by melloware** [comment]
@tomhendra I reproduced with your Vite what the final outcome will be its now wrapped in a `<span className="p-button-icon p-c p-button-icon-right">` and you can see the funky spacing.  Let me know what you find out.

**Comment by tomhendra** [comment]
It's due to the way in which the spans render their respective children in CSS flow layout. 

Because span elements align text centrally on the Y axis by default it's causing 'label` to be aligned centrally (we'd use `vertical-align` to change the behaviour).

The SVG element however isn't text, and doesn't care what the span says about y axis alignment. Instead, it's being rendered in the default position for flow layout within the parent span's containing box — top-left.

To fix the funkiness we need to change the layout mode of the span containing the SVG — slap on a `display: flex` and be done with it, or wrap both the SVG and label in a singular span to be arguably cleaner, although this could interfere with `iconPos` and the badge. 


https://user-images.githubusercontent.com/32566274/212550499-faf71924-8040-4043-8e0d-64f487e49084.mov

Let me know if I can be of any more help.

**Comment by melloware** [comment]
Ok let me look thanks for the hints!

**Comment by tomhendra** [comment]
Awesome! Thank you, @melloware.

**Comment by melloware** [comment]
Thanks for the assist!

**Comment by melloware** [comment]
@tomhendra can you try 9.3.0 i believe this is fixed now.  See the docs: https://primereact.org/customicons/

They support any icons including SVG

**Comment by tomhendra** [comment]
Many thanks @melloware

**Comment by melloware** [comment]
Will close for now let me know if not and I can re-open it.

**Comment by Holgrabus** [comment]
Hello, I think that issue is still not fixed. At least, I'm using <FontAwesomeIcon> and I have on margin and the position is not taken in account.

**Comment by melloware** [comment]
@Holgrabus create a StackBlitz reproducer and open a new ticket against PrimeReact 10.8.0 then...
