### ISSUE TITLE
Calendar: lag when navigating between months

### ISSUE THREAD

**Issue by djapal** [primefaces/primereact#5202]
### Describe the bug

Just saw it using latest version of primereact.
I also noticed the same behavior at official website.
When you click on textbox to load the calendar, it has a lag and also when you try to navigation between months you can see a lag ranging from 1 to 2 seconds.
Same senario with version 8.7 (i selected the version from the up right dropdown at the website) and loading and navigation are instant.
This happens in firefox though, chrome for some reason is OK.
https://primereact.org/calendar/

### PrimeReact version

10.0.7

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox 119

### Steps to reproduce the behavior

1. Go to https://primereact.org/calendar/
2. Just try to load a calendar and navigation between months

**Comment by melloware** [comment]
Similar to this Firefox issue: https://github.com/primefaces/primereact/issues/5189

**Comment by djapal** [comment]
`git checkout d28546906d46ecf0ffb4a0c42b897075307ca0be
npm run build
npm run dev
`

all work fine in firefox

`git checkout fcbeb00b6fb607c043074e7f1b8ce3360cd53183
npm run build
npm run dev
`
causes the lag.
It seems that the guilty commit is fcbeb00b6fb607c043074e7f1b8ce3360cd53183

**Comment by melloware** [comment]
Excellent debugging! Let me look.

**Comment by melloware** [comment]
Looks like its Firefox not playing nicely with Google Tag Manager: https://stackoverflow.com/questions/62478071/firefox-enhanced-privacy-protection-is-blocking-datalayer-push-to-google-tag-man

![image](https://github.com/primefaces/primereact/assets/4399574/5428467a-2343-4e27-b2f2-c5efe5515559)

**Comment by melloware** [comment]
Try enabling tracking: https://developer.mozilla.org/en-US/docs/Web/Privacy/Firefox_tracking_protection

**Comment by melloware** [comment]
@djapal also `npm run dev` the Google Tag Manager should not be running at all it only runs in production mode?

**Comment by djapal** [comment]
> @djapal also `npm run dev` the Google Tag Manager should not be running at all it only runs in production mode?

it seems to happen even if i comment out the tag manager tag and import.

i also get this error in build 

```
Error occurred prerendering page "/organizationchart". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: nodeChildLength is not defined
```

**Comment by melloware** [comment]
@djapal that is why I was thinking it wasn't that commit.   

As for your error you get that running `npm run dev` ?

**Comment by djapal** [comment]
> @djapal that is why I was thinking it wasn't that commit.
> 
> As for your error you get that running `npm run dev` ?

exact log 
```
PS C:\DEVELOPMENT\GITHUB\primereact> npm run dev

> primereact@10.0.0-SNAPSHOT dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1244 ms (574 modules)
wait  - compiling /calendar (client and server)...
event - compiled client and server successfully in 629 ms (827 modules)
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 497 ms (830 modules)

 *  History restored 


> primereact@10.0.0-SNAPSHOT build
> next build

info  - Linting and checking validity of types
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/140)ReferenceError: nodeChildLength is not defined      
    at lineRight (C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:225:55)
    at ObjectUtils.getJSXElement (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\1975.js:1211:39)
    at getOptionValue (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\4645.js:737:205)
    at cx (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\4645.js:780:40)
    at C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:359:36
    at Array.map (<anonymous>)
    at createLinesMiddle (C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:352:76)
    at C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:476:25
    at Wc (C:\DEVELOPMENT\GITHUB\primereact\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\DEVELOPMENT\GITHUB\primereact\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)

Error occurred prerendering page "/organizationchart". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: nodeChildLength is not defined
    at lineRight (C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:225:55)
    at ObjectUtils.getJSXElement (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\1975.js:1211:39)
    at getOptionValue (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\4645.js:737:205)
    at cx (C:\DEVELOPMENT\GITHUB\primereact\.next\server\chunks\4645.js:780:40)
    at C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:359:36
    at Array.map (<anonymous>)
    at createLinesMiddle (C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:352:76)
    at C:\DEVELOPMENT\GITHUB\primereact\.next\server\pages\organizationchart.js:476:25
    at Wc (C:\DEVELOPMENT\GITHUB\primereact\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\DEVELOPMENT\GITHUB\primereact\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
info  - Generating static pages (140/140)

> Build error occurred
Error: Export encountered errors on following paths:
        /organizationchart
    at C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\export\index.js:404:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\trace\trace.js:79:20)
    at async C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\build\index.js:1230:21
    at async Span.traceAsyncFn (C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\trace\trace.js:79:20)
    at async C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\build\index.js:1092:17
    at async Span.traceAsyncFn (C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\trace\trace.js:79:20)
    at async Object.build [as default] (C:\DEVELOPMENT\GITHUB\primereact\node_modules\next\dist\build\index.js:65:29)
```

but this is the commit where the lag is first seen

**Comment by melloware** [comment]
Weird I can't reproduce even if I go to the Organization Chart page.

```shell
C:\dev\primetek\primereact>npm run dev

> primereact@10.0.10-SNAPSHOT dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1042 ms (572 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 569 ms (800 modules)
wait  - compiling /installation...
event - compiled client and server successfully in 407 ms (843 modules)
wait  - compiling /organizationchart (client and server)...
event - compiled client and server successfully in 372 ms (882 modules)
```

**Comment by melloware** [comment]
right but something has been fixed since then since the org chart is no longer an issue.  So there is no point dwelling on that issue right?

**Comment by djapal** [comment]
yes yes it's ok, I was thinking maybe it created another problem at that specific build.

**Comment by melloware** [comment]
Yep just trying to narrow down exactly what the cause is but the GTagManager would be strange because it doesn't even get rendered in Dev mode?

**Comment by djapal** [comment]
yes correct. i disabled it, rebuilt the project and  the lag still exists

**Comment by melloware** [comment]
Hmm I am using Firefox looking at the latest showcase and I see no lag?  https://primereact.org/calendar/#minmax

**Comment by djapal** [comment]
> Hmm I am using Firefox looking at the latest showcase and I see no lag? https://primereact.org/calendar/#minmax

i think it's better than the time i opened the issue but you still can see some lag compared to chrome. I also noticed that with dropdown list when having lots of objects (~600)

**Comment by djapal** [comment]
> Hmm I am using Firefox looking at the latest showcase and I see no lag? https://primereact.org/calendar/#minmax

i spotted the problem. it was between these 2 commits for ripple

01b9ba8cc slow rendering, calendar OK
521fa2090 slow rendering, calendar not OK

same happens with latest commit e135dc225. calendar month navigation with ripple effect enables is slow. if you disable the ripple effect, it is normal/fast in firefox.

**Comment by melloware** [comment]
Great debugging its definitely the Ripple effect!    If you disable Ripple in the Showcase you will see your performance go way up. Can you confirm?

**Comment by djapal** [comment]
> Great debugging its definitely the Ripple effect! If you disable Ripple in the Showcase you will see your performance go way up. Can you confirm?

just tested in showcase site and it happens as i told you.
 disabled ripple effect, smooth experience
 enabled ripple effect, lag

**Comment by melloware** [comment]
PR submitted.
