### ISSUE TITLE
Tabview: There is No style when use PrimeReact & Tailwind

### ISSUE THREAD

**Issue by foreverzmy** [primefaces/primereact#5445]
### Describe the bug

 I am encountering a styling issue with the TabView component in PrimeReact when using it in conjunction with Tailwind CSS. The styles of the TabView component appear to be distorted and do not align properly when Tailwind CSS is applied. This issue seems to be specific to the interaction between PrimeReact and Tailwind CSS.

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-q51etp

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
cc @Dalorzo can you look at this one and help determine why the Tailwind styles are not being applied?

**Comment by melloware** [comment]
I think its similar to this one: https://github.com/primefaces/primereact/issues/5395

**Comment by Dalorzo** [comment]
@melloware I was not able to find the exact root cause. 

However, what is happening is that `TabView` is overriding or not add the the`TabPanelPassThroughOptions` of the TabPanel based on what is Tailwind. 

So, what I did was passing `pt={Tailwind.tabpanel}` directly to the TabPanel, however, this also failed because there is a bug in the Tailwind of TabPanel, but I implemented a fixed version and it worked passing my `pt tailwind version`.

```html
 <TabView>
            <TabPanel header="Header I" pt={MyTailwind.tabpanel}>
              <p className="m-0">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                deserunt mollit anim id est laborum.
              </p>
            </TabPanel>
            ```
            
            The issue in TabPanel Tailwind:
            The correct signature for `headerAction` is ` headerAction: ({ parent, props }: TabPanelPassThroughMethodOptions)`
            However, the implementation uses: `context` and `parent.state.d_activeIndex` which is not correct based on the type it should be `parent.state.activeIndex`, however, `props` does not provide access to the `selectedIndex` that is another issue
            
            ```typescript
             headerAction: ({ parent, context }) => ({
                className: classNames(
                    'items-center cursor-pointer flex overflow-hidden relative select-none text-decoration-none user-select-none', // Flex and overflow styles.
                    'border-b-2 p-5 font-bold rounded-t-md transition-shadow duration-200 m-0', // Border, padding, font, and transition styles.
                    'transition-colors duration-200', // Transition duration style.
                    'focus:outline-none focus:outline-offset-0 focus:shadow-[inset_0_0_0_0.2rem_rgba(191,219,254,1)] dark:focus:shadow-[inset_0_0_0_0.2rem_rgba(147,197,253,0.5)]', // Focus styles.
                    {
                        'border-gray-300 bg-white text-gray-700 hover:bg-white hover:border-gray-400 hover:text-gray-600 dark:bg-gray-900 dark:border-blue-900/40 dark:text-white/80 dark:hover:bg-gray-800/80':
                            parent.state.d_activeIndex !== context.index, // Condition-based hover styles.
                        'bg-white border-blue-500 text-blue-500 dark:bg-gray-900 dark:border-blue-300 dark:text-blue-300': parent.state.d_activeIndex === context.index // Condition-based active styles.
                    }
                ),
                ```

**Comment by melloware** [comment]
awesome i think i know how to fix this!

**Comment by LB-sx** [comment]
Hello, I'm currently running primereact in version 10.6.6 and 10.7.0 and still not have the styles with Tailwind:

![image](https://github.com/primefaces/primereact/assets/175269290/266039da-b447-4751-8d6e-30ceeb6cc839)

Navbar.tsx:
![image](https://github.com/primefaces/primereact/assets/175269290/07ea7740-458b-4390-b6e0-745920f68dd7)

PrimeRactProvider config:
![image](https://github.com/primefaces/primereact/assets/175269290/e9d7814e-afb9-4107-9f87-3d69b114ac33)

#5445, #5567 marked the problem as closed and solved but it is not looking like to be solved, any idea on why it would happen on the current version?

**Comment by melloware** [comment]
Please open a new ticket with reproducer.
