### ISSUE TITLE
Calendar: When `enabledDates` array is set, user will get stuck on month/year selection

### ISSUE THREAD

**Issue by ArsenicBismuth** [primefaces/primereact#5662]
### Describe the bug

The code I use to populate the `enabledDates` (basically from today till 14 days from now):

```
  // Availability
  const enabledDates = [];
  const today = new Date();
  for (let i = 0; i <= 14; i++) {
    let date = new Date();
    date.setDate(today.getDate() + i);
    enabledDates.push(date);
  }
```

What happens to the calendar in day-view, normal:

![image](https://github.com/primefaces/primereact/assets/19264532/b786efd5-d715-40b7-841c-ede1d038fa99)

![image](https://github.com/primefaces/primereact/assets/19264532/8808b071-010d-47af-97d9-47e7cce66e16)

What happens when users click on the month/year, they're stuck:

![image](https://github.com/primefaces/primereact/assets/19264532/dd0584ab-6ac1-44dd-88b5-0d02b94aa493)

![image](https://github.com/primefaces/primereact/assets/19264532/a80ef2f9-0d59-4c48-8285-9e7f2cc0c46d)

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

User can go back to the respective year/month where the dates are enabled.

Or, if that's too complex (as there might be multiple, separated dates), never disable year or month selection even if `enabledDates` array is set.

**Comment by melloware** [comment]
@kl-nevermore just did a lot of work in main to fix this: https://github.com/primefaces/primereact/issues/5581

This may already be fixed in main will have to test.

**Comment by ArsenicBismuth** [comment]
Ahhhh niceee, will try that one. Finally I didn't get blocked by a bug this time 😅.

**Comment by melloware** [comment]
OK just tested against Main it looks good.

![image](https://github.com/primefaces/primereact/assets/4399574/06058a71-03f7-40af-a6a5-42b5201525cb)

![image](https://github.com/primefaces/primereact/assets/4399574/98780904-489c-4418-956d-532c55c572d4)

**Comment by jerlam06** [comment]
@melloware 10.2.1 here and still having the exact same issue. When I feed the Calendar with enabledDates, then the user is stuck in the month or year selector (if clicked) without any way to going back (a page refresh is needed). Event the months/years that have selectable dates do not appear selectable in the month/year picker.
