### ISSUE TITLE
Listbox virtualscroller doesnt display data

### ISSUE THREAD

**Issue by SenexCrenshaw** [primefaces/primereact#6494]
### Describe the bug

i get just a few entries and the data never populates. dropdown virtual scroll works great. 
You can see this in the demo at https://primereact.org/listbox/#virtualscroll scroll mid way and nothing happens. 

### Reproducer

https://primereact.org/listbox/#virtualscroll

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Go to the demo
https://primereact.org/listbox/#virtualscroll
scroll mid way down and data never appears.

### Expected behavior

data to appear

**Comment by ujshaikh** [comment]
@melloware 
I also faced this issue, please assign it to me. I will try to fix and raise PR soon

**Comment by melloware** [comment]
Done

**Comment by SenexCrenshaw** [comment]
thanks for looking into this

**Comment by SenexCrenshaw** [comment]
Anything I can do to help???

**Comment by ujshaikh** [comment]
Apologize
Needs someone help, I am on medical leaves

**Comment by CodrinSocol** [comment]
This issue still occurs 2 years later. A suitable alternative I found was to use the `MultiSelect` component instead.
