### ISSUE TITLE
Tree: The Tree component's collapse functionality is not working

### ISSUE THREAD

**Issue by rakeshvermak** [primefaces/primereact#7392]
### Describe the bug

Collapse is not working after Search operation

### Reproducer

https://stackblitz.com/edit/vitejs-vite-tqykhs?file=src%2Fservice%2FNodeService.jsx,src%2FApp.jsx

### System Information

```Shell
primereact version: 10.5.3
react version: 17.x
```

### Steps to reproduce the behavior

Go to Tree Node view.
Search for some text in the search bar.
Tree expands with data of all folders.
If we want to collapse other than our folders to see all the data. It is not working. We are unable to collapse the project tree.

### Expected behavior

It is expected to collapse the project tree node when search operation is performed.

**Comment by rakeshvermak** [comment]
Screenshot attached for your reference.
![image](https://github.com/user-attachments/assets/2b75da07-ddef-4132-89f3-f8782f1a3b61)

**Comment by melloware** [comment]
Its working fine here in 10.8.4: https://primereact.org/tree/ ???

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/7232

**Comment by melloware** [comment]
Fixed for next release

**Comment by rakeshvermak** [comment]
As per the PrimeReact community, @melloware  added this issue to the 10.9.2 milestone on January 3. I have upgraded to version 10.9.2 and also tested it with 10.9.4, but the Tree component's collapse functionality is still not working.

Issue: https://github.com/primefaces/primereact/issues/7392
@KumJungMin  – Pull Request: https://github.com/primefaces/primereact/pull/7282
